In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from ISLP import load_data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

df = load_data("Weekly")

%matplotlib inline

In [8]:
df

Year   Lag1   Lag2   Lag3   Lag4   Lag5    Volume  Today Direction  Dir
0     1990  0.816  1.572 -3.936 -0.229 -3.484  0.154976 -0.270      Down    0
1     1990 -0.270  0.816  1.572 -3.936 -0.229  0.148574 -2.576      Down    0
2     1990 -2.576 -0.270  0.816  1.572 -3.936  0.159837  3.514        Up    1
3     1990  3.514 -2.576 -0.270  0.816  1.572  0.161630  0.712        Up    1
4     1990  0.712  3.514 -2.576 -0.270  0.816  0.153728  1.178        Up    1
...    ...    ...    ...    ...    ...    ...       ...    ...       ...  ...
1084  2010 -0.861  0.043 -2.173  3.599  0.015  3.205160  2.969        Up    1
1085  2010  2.969 -0.861  0.043 -2.173  3.599  4.242568  1.281        Up    1
1086  2010  1.281  2.969 -0.861  0.043 -2.173  4.835082  0.283        Up    1
1087  2010  0.283  1.281  2.969 -0.861  0.043  4.454044  1.034        Up    1
1088  2010  1.034  0.283  1.281  2.969 -0.861  2.707105  0.069        Up    1

[1089 rows x 10 columns]

In [44]:
df['Dir'] = (df['Direction'] == "Up").astype(int)

In [54]:
lr = LogisticRegression(C=10**5)
X = df[['Lag1','Lag2']]
y = df['Dir']
mod = lr.fit(X,y)
mod.coef_

array([[-0.03872222,  0.0602483 ]])

In [48]:
X_one = df[['Lag1','Lag2']][1:]
y_one = df['Dir'][1:]
mod = lr.fit(X_one,y_one)
mod.coef_

array([[-0.03843317,  0.06084763]])

In [50]:
mod.predict([X.iloc[0]]),y[0]
# This observation was not correctly classified

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


(array([1]), 0)

In [59]:
n = len(X)
errors = np.zeros(n)

for i in range(n):
    one_out  = ~X.index.isin([i])
    # i.
    mod.fit(X[one_out], y[one_out])
    # ii. iii. iv.
    if mod.predict([X.iloc[i]]) != y[i]:
        errors[i] = 1


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X 

In [60]:
errors.mean()

0.44995408631772266